CREATE TABLE Customer (
	cid			BIGINT			PRIMARY KEY AUTO_INCREMENT,
	name		VARCHAR(10)		NOT NULL,
	ssn			VARCHAR(14)		NOT NULL,
	regDate		TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP
)AUTO_INCREMENT = 1001;

INSERT INTO Customer (name, ssn) VALUES ('홍길동', '801225-1234567');

CREATE TABLE Account (
	aid				BIGINT		PRIMARY KEY AUTO_INCREMENT,
	accType			char(1)		NOT NULL	DEFAULT 'S',
	balance			DOUBLE		NOT NULL	DEFAULT 0.0,
	interestRate	DOUBLE		NOT NULL	DEFAULT 0.0,
	overdraftAmount	DOUBLE		NOT NULL	DEFAULT 0.0,
	customerID		BIGINT		NOT NULL,
	regDate			TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP
	CONSTRAINT Account_customerId_FK FOREIGN KEY (customerId) REFERENCES Customer(cid)
)AUTO_INCREMENT = 3001;

INSERT INTO Account (accType, balance, interestRate, overdraftAmount) VALUES ('C', 20000.0, 0.03, 2000.0);
